services:
  e-commerce-discovery-service:
    build: ./discovery-service
    container_name: e-commerce-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
  e-commerce-config-service:
    build: ./config-service
    container_name: e-commerce-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      -DISCOVERY_SERVICE_URL: http://e-commerce-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
    depends_on:
      e-commerce-discovery-service:
        condition: service_healthy
  e-commerce-customer-service:
    build: ./customer-service
    container_name: e-commerce-customer-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      -DISCOVERY_SERVICE_URL: http://e-commerce-discovery-service:8761/eureka
      -CONFIG_SERVICE_URL: http://e-commerce-config-service:9999
    depends_on:
      e-commerce-config-service:
        condition: service_healthy
  e-commerce-inventory-service:
    build: ./inventory-service
    container_name: e-commerce-inventory-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      -DISCOVERY_SERVICE_URL: http://e-commerce-discovery-service:8761/eureka
      -CONFIG_SERVICE_URL: http://e-commerce-config-service:9999
    depends_on:
      e-commerce-config-service:
        condition: service_healthy
  e-commerce-billing-service:
    build: ./billing-service
    container_name: e-commerce-billing-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      -DISCOVERY_SERVICE_URL: http://e-commerce-discovery-service:8761/eureka
      -CONFIG_SERVICE_URL: http://e-commerce-config-service:9999
    depends_on:
      e-commerce-config-service:
        condition: service_healthy
  e-commerce-order-service:
    build: ./order-service
    container_name: e-commerce-order-service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      -DISCOVERY_SERVICE_URL: http://e-commerce-discovery-service:8761/eureka
      -CONFIG_SERVICE_URL: http://e-commerce-config-service:9999
    depends_on:
      e-commerce-config-service:
        condition: service_healthy

